# -*- coding: utf-8 -*-
"""canDetectMissing(grounding dino).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1RY8Mg8u-wikDl10RcY4VDDY9lQ-n-D08
"""

import torch
print(torch.cuda.is_available())  # Should return True
print(torch.cuda.get_device_name(0))  # Should show 'Tesla T4'

!pip install torch torchvision transformers requests pillow

import requests
import torch
from PIL import Image
from transformers import AutoProcessor, AutoModelForZeroShotObjectDetection

# Define model and device
model_id = "IDEA-Research/grounding-dino-tiny"
device = "cuda" if torch.cuda.is_available() else "cpu"

# Load processor and model
processor = AutoProcessor.from_pretrained(model_id)
model = AutoModelForZeroShotObjectDetection.from_pretrained(model_id).to(device)

import os
from PIL import Image

# Define dataset path
dataset_folder = "/content/dataset_folders/unmatched_templates"

# Get a sorted list of image files (assuming JPG format)
image_files = sorted([f for f in os.listdir(dataset_folder) if f.endswith(".jpg")])[:10]  # Only first 10 images

# Iterate through all images and display them
for image_name in image_files:
    image_path = os.path.join(dataset_folder, image_name)
    image = Image.open(image_path).convert("RGB")
    image.show()  # Display image in Colab
    print(f"Displayed: {image_name}")

import zipfile
import os
import pandas as pd
import json

# Step 1: Unzip the file
zip_file_path = "/content/unmatched_templates.zip"  # Change this to your ZIP file path
extract_to = "/content/dataset_folders"  # Folder to extract contents

# Extract ZIP file
with zipfile.ZipFile(zip_file_path, 'r') as zip_ref:
    zip_ref.extractall(extract_to)

print(f"✅ Unzipped to: {extract_to}")

# Step 2: List all files inside
file_list = os.listdir(extract_to)
print("\n📂 Files in the dataset folder:")
for file in file_list:
    print(" -", file)

# Step 3: Check if any CSV or JSON files are present
for file in file_list:
    file_path = os.path.join(extract_to, file)

    if file.endswith(".csv"):
        print(f"\n📄 Preview of {file}:")
        df = pd.read_csv(file_path)
        print(df.head())  # Show first few rows

    elif file.endswith(".json"):
        print(f"\n📄 Preview of {file}:")
        with open(file_path, "r") as f:
            data = json.load(f)
            print(json.dumps(data, indent=2)[:500])  # Print first 500 characters

# Zero-shot object detection labels
text_labels = [["Fork-Lift", "yellow hardhat","Mask", "safety vest", "shoes","person","Safety Cone", "Fire", "Smoke","Choke","Safety Harness"]]

for image_name in image_files:
    image_path = os.path.join(dataset_folder, image_name)
    image = Image.open(image_path).convert("RGB")

    # Preprocess input
    inputs = processor(images=[image], text=text_labels, return_tensors="pt").to(device)

    # Run inference without gradient calculations
    with torch.no_grad():
        outputs = model(**inputs)

    print(f"Processed: {image_name}")

import os
import cv2
import torch
from PIL import Image
import matplotlib.pyplot as plt
import matplotlib.patches as patches

# Split person bbox into head, torso, and feet
def split_person_bbox(bbox, image_height, min_visible_height_ratio=0.6):
    x_min, y_min, x_max, y_max = bbox
    height = y_max - y_min
    bbox_bottom_visible = y_max >= int(image_height * min_visible_height_ratio)

    head = [x_min, y_min, x_max, int(y_min + 0.20 * height)]
    torso = [x_min, int(y_min + 0.20 * height), x_max, int(y_min + 0.80 * height)]
    feet = [x_min, int(y_min + 0.80 * height), x_max, y_max]

    regions = {"head": head, "torso": torso}
    if bbox_bottom_visible:
        regions["feet"] = feet
    return regions

# Draw bounding boxes and labels on the image
def draw_boxes_with_labels(image, detections, split_regions_list=None, save_path=None):
    fig, ax = plt.subplots(1, figsize=(10, 8))
    ax.imshow(image)

    for box, score, label in detections:
        x_min, y_min, x_max, y_max = box
        width, height = x_max - x_min, y_max - y_min

        rect = patches.Rectangle(
            (x_min, y_min), width, height, linewidth=2, edgecolor='red', facecolor='none'
        )
        ax.add_patch(rect)
        ax.text(
            x_min, y_min - 5,
            f"{label}: {round(score, 2)}",
            color='red', fontsize=10, fontweight='bold'
        )

    if split_regions_list:
        colors = {"head": "blue", "torso": "green", "feet": "purple"}
        for split_regions in split_regions_list:
            for region_name, region_box in split_regions.items():
                x_min, y_min, x_max, y_max = region_box
                width, height = x_max - x_min, y_max - y_min
                rect = patches.Rectangle(
                    (x_min, y_min), width, height,
                    linewidth=2, edgecolor=colors.get(region_name, 'gray'), facecolor='none'
                )
                ax.add_patch(rect)
                ax.text(
                    x_min, y_min - 5,
                    region_name,
                    color=colors.get(region_name, 'gray'), fontsize=10
                )

    plt.axis("off")

    if save_path:
        plt.savefig(save_path, bbox_inches='tight', pad_inches=0.1)

    plt.show()
    plt.close(fig)

# Process each image
output_folder = "annotated_images"
os.makedirs(output_folder, exist_ok=True)

for image_name in image_files:
    image_path = os.path.join(dataset_folder, image_name)
    image_pil = Image.open(image_path).convert("RGB")
    image_cv = cv2.imread(image_path)

    inputs = processor(images=[image_pil], text=text_labels, return_tensors="pt").to(device)

    with torch.no_grad():
        outputs = model(**inputs)

    results = processor.post_process_grounded_object_detection(
        outputs,
        inputs.input_ids,
        box_threshold=0.5,
        text_threshold=0.3,
        target_sizes=[image_pil.size[::-1]]
    )

    detections = []
    person_split_regions = []

    for box, score, label in zip(results[0]["boxes"], results[0]["scores"], results[0]["labels"]):
        box = list(map(int, box.tolist()))
        detections.append((box, score.item(), label))

        if label.lower() == "person":
            split_regions = split_person_bbox(box, image_cv.shape[0])
            person_split_regions.append(split_regions)

    print(f"Detected {len(detections)} objects in {image_name}")
    save_path = os.path.join(output_folder, f"{image_name}")
    draw_boxes_with_labels(
        image_pil,
        detections,
        split_regions_list=person_split_regions,
        save_path=save_path
    )

import matplotlib.pyplot as plt
import matplotlib.patches as patches

def is_yellow_hardhat_present(head_box, other_boxes, other_labels, iou_threshold=0.1):
    def compute_iou(boxA, boxB):
        xA = max(boxA[0], boxB[0])
        yA = max(boxA[1], boxB[1])
        xB = min(boxA[2], boxB[2])
        yB = min(boxA[3], boxB[3])
        interArea = max(0, xB - xA) * max(0, yB - yA)

        boxAArea = (boxA[2] - boxA[0]) * (boxA[3] - boxA[1])
        boxBArea = (boxB[2] - boxB[0]) * (boxB[3] - boxB[1])
        iou = interArea / float(boxAArea + boxBArea - interArea + 1e-5)
        return iou

    for label, box in zip(other_labels, other_boxes):
        if label.lower() == "yellow hardhat":
            iou = compute_iou(head_box, list(map(int, box.tolist())))
            if iou >= iou_threshold:
                return True
    return False



# Modified loop to check for hardhat
for image_name in image_files:
    image_path = os.path.join(dataset_folder, image_name)
    image = Image.open(image_path).convert("RGB")
    image_cv = cv2.imread(image_path)

    inputs = processor(images=[image], text=text_labels, return_tensors="pt").to(device)

    with torch.no_grad():
        outputs = model(**inputs)

    results = processor.post_process_grounded_object_detection(
        outputs, inputs.input_ids,
        box_threshold=0.5, text_threshold=0.3,
        target_sizes=[image.size[::-1]]
    )

    all_boxes = results[0]["boxes"]
    all_scores = results[0]["scores"]
    all_labels = results[0]["labels"]

    for box, score, label in zip(all_boxes, all_scores, all_labels):
        if label.lower() == "person":
            box = list(map(int, box.tolist()))
            print(f"Detected {label} with confidence {round(score.item(), 3)} at {box}")
            regions = split_person_bbox(box, image_cv.shape[0])
            #draw_regions(image_cv.copy(), regions, f"{image_name} - Split Regions")

            # Check for yellow hardhat in the head region
            head_box = regions["head"]
            yellow_hardhat_present = is_yellow_hardhat_present(head_box, all_boxes, all_labels)
            status = "PRESENT" if yellow_hardhat_present else "MISSING"
            print(f"Yellow Hardhat: {status} in {image_name}")

def is_safety_vest_present(torso_box, other_boxes, other_labels, iou_threshold=0.1):
    def compute_iou(boxA, boxB):
        xA = max(boxA[0], boxB[0])
        yA = max(boxA[1], boxB[1])
        xB = min(boxA[2], boxB[2])
        yB = min(boxA[3], boxB[3])
        interArea = max(0, xB - xA) * max(0, yB - yA)

        boxAArea = (boxA[2] - boxA[0]) * (boxA[3] - boxA[1])
        boxBArea = (boxB[2] - boxB[0]) * (boxB[3] - boxB[1])
        iou = interArea / float(boxAArea + boxBArea - interArea + 1e-5)
        return iou

    for label, box in zip(other_labels, other_boxes):
        if label.lower() == "safety vest":
            iou = compute_iou(torso_box, list(map(int, box.tolist())))
            if iou >= iou_threshold:
                return True
    return False

# Example loop to detect safety vest
for image_name in image_files:
    image_path = os.path.join(dataset_folder, image_name)
    image = Image.open(image_path).convert("RGB")
    image_cv = cv2.imread(image_path)

    inputs = processor(images=[image], text=text_labels, return_tensors="pt").to(device)

    with torch.no_grad():
        outputs = model(**inputs)

    results = processor.post_process_grounded_object_detection(
        outputs, inputs.input_ids,
        box_threshold=0.5, text_threshold=0.3,
        target_sizes=[image.size[::-1]]
    )

    all_boxes = results[0]["boxes"]
    all_scores = results[0]["scores"]
    all_labels = results[0]["labels"]

    for box, score, label in zip(all_boxes, all_scores, all_labels):
        if label.lower() == "person":
            box = list(map(int, box.tolist()))
            print(f"Detected {label} with confidence {round(score.item(), 3)} at {box}")
            regions = split_person_bbox(box, image_cv.shape[0])
            #draw_boxes_with_labels(image, detections, split_regions=None)


            # Check for safety vest in the torso region
            torso_box = regions["torso"]
            safety_vest_present = is_safety_vest_present(torso_box, all_boxes, all_labels)
            vest_status = "PRESENT" if safety_vest_present else "MISSING"
            print(f"Safety Vest: {vest_status} in {image_name}")

def is_safety_shoes_present(feet_box, other_boxes, other_labels, iou_threshold=0.1):
    def compute_iou(boxA, boxB):
        xA = max(boxA[0], boxB[0])
        yA = max(boxA[1], boxB[1])
        xB = min(boxA[2], boxB[2])
        yB = min(boxA[3], boxB[3])
        interArea = max(0, xB - xA) * max(0, yB - yA)

        boxAArea = (boxA[2] - boxA[0]) * (boxA[3] - boxA[1])
        boxBArea = (boxB[2] - boxB[0]) * (boxB[3] - boxB[1])
        iou = interArea / float(boxAArea + boxBArea - interArea + 1e-5)
        return iou

    for label, box in zip(other_labels, other_boxes):
        if label.lower() == "shoes":
            iou = compute_iou(feet_box, list(map(int, box.tolist())))
            if iou >= iou_threshold:
                return True
    return False

# Example loop to detect safety shoes
for image_name in image_files:
    image_path = os.path.join(dataset_folder, image_name)
    image = Image.open(image_path).convert("RGB")
    image_cv = cv2.imread(image_path)

    inputs = processor(images=[image], text=text_labels, return_tensors="pt").to(device)

    with torch.no_grad():
        outputs = model(**inputs)

    results = processor.post_process_grounded_object_detection(
        outputs, inputs.input_ids,
        box_threshold=0.5, text_threshold=0.3,
        target_sizes=[image.size[::-1]]
    )

    all_boxes = results[0]["boxes"]
    all_scores = results[0]["scores"]
    all_labels = results[0]["labels"]

    for box, score, label in zip(all_boxes, all_scores, all_labels):
        if label.lower() == "person":
            box = list(map(int, box.tolist()))
            print(f"Detected {label} with confidence {round(score.item(), 3)} at {box}")
            regions = split_person_bbox(box, image_cv.shape[0])
            #draw_regions(image_cv.copy(), regions, f"{image_name} - Split Regions")

            # Check for safety shoes in the feet region
            if "feet" in regions:
                feet_box = regions["feet"]
                safety_shoes_present = is_safety_shoes_present(feet_box, all_boxes, all_labels)
                shoes_status = "PRESENT" if safety_shoes_present else "MISSING"
                print(f"Safety Shoes: {shoes_status} in {image_name}")

import os
from PIL import Image

# Class names to class IDs (customize as needed)
class_mapping = {
    "Fork-Lift": 0,
    "yellow hardhat": 1,
    "Mask": 2,
    "safety vest": 3,
    "shoes": 4,
    "person": 5,
    "Safety Cone": 6,
    "Fire": 7,
    "Smoke": 8,
    "Choke": 9,
    "Safety Harness": 10
}


# Output folder for YOLO format bounding boxes
output_folder = "yolo_annotations"
os.makedirs(output_folder, exist_ok=True)

# Loop over all images
for image_name in image_files:
    image_path = os.path.join(dataset_folder, image_name)
    image = Image.open(image_path).convert("RGB")
    W, H = image.size

    # Process input with class labels
    inputs = processor(images=[image], text=list(class_mapping.keys()), return_tensors="pt").to(device)

    # Model inference
    with torch.no_grad():
        outputs = model(**inputs)

    # Post-process model outputs
    results = processor.post_process_grounded_object_detection(
        outputs,
        inputs.input_ids,
        threshold=0.5,
        text_threshold=0.3,
        target_sizes=[image.size[::-1]]
    )

    result = results[0]

    # Save to YOLO format
    output_file = os.path.join(output_folder, f"{os.path.splitext(image_name)[0]}.txt")
    with open(output_file, "w") as f:
        for box, label in zip(result["boxes"], result["labels"]):
            x_min, y_min, x_max, y_max = box.tolist()

            # Get class ID from label
            class_id = class_mapping.get(label, 0)  # Default to 0 if label not found

            # Convert to YOLO format
            x_center = ((x_min + x_max) / 2) / W
            y_center = ((y_min + y_max) / 2) / H
            width = (x_max - x_min) / W
            height = (y_max - y_min) / H

            # Write the YOLO line
            f.write(f"{class_id} {x_center:.6f} {y_center:.6f} {width:.6f} {height:.6f}\n")

print(f"YOLO format annotations saved in the '{output_folder}' folder.")

