# -*- coding: utf-8 -*-
"""zeroShot3(grounding dino).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1oLSAdq-vK1d50vPDX1ecSvKfdAS1czYc
"""

import torch
print(torch.cuda.is_available())  # Should return True
print(torch.cuda.get_device_name(0))  # Should show 'Tesla T4'

!pip install torch torchvision transformers requests pillow

import requests
import torch
from PIL import Image
from transformers import AutoProcessor, AutoModelForZeroShotObjectDetection

# Define model and device
model_id = "IDEA-Research/grounding-dino-tiny"
device = "cuda" if torch.cuda.is_available() else "cpu"

# Load processor and model
processor = AutoProcessor.from_pretrained(model_id)
model = AutoModelForZeroShotObjectDetection.from_pretrained(model_id).to(device)

import os
from PIL import Image

# Define dataset path
dataset_folder = "/content/dataset_folder/data_"

# Get a sorted list of image files (assuming JPG format)
image_files = sorted([f for f in os.listdir(dataset_folder) if f.endswith(".jpg")])[:10]  # Only first 10 images

# Iterate through all images and display them
for image_name in image_files:
    image_path = os.path.join(dataset_folder, image_name)
    image = Image.open(image_path).convert("RGB")
    image.show()  # Display image in Colab
    print(f"Displayed: {image_name}")

import zipfile
import os
import pandas as pd
import json

# Step 1: Unzip the file
zip_file_path = "/content/data_.zip"  # Change this to your ZIP file path
extract_to = "/content/dataset_folder"  # Folder to extract contents

# Extract ZIP file
with zipfile.ZipFile(zip_file_path, 'r') as zip_ref:
    zip_ref.extractall(extract_to)

print(f"✅ Unzipped to: {extract_to}")

# Step 2: List all files inside
file_list = os.listdir(extract_to)
print("\n📂 Files in the dataset folder:")
for file in file_list:
    print(" -", file)

# Step 3: Check if any CSV or JSON files are present
for file in file_list:
    file_path = os.path.join(extract_to, file)

    if file.endswith(".csv"):
        print(f"\n📄 Preview of {file}:")
        df = pd.read_csv(file_path)
        print(df.head())  # Show first few rows

    elif file.endswith(".json"):
        print(f"\n📄 Preview of {file}:")
        with open(file_path, "r") as f:
            data = json.load(f)
            print(json.dumps(data, indent=2)[:500])  # Print first 500 characters

# Zero-shot object detection labels
text_labels = [["a remote control", "a human head", "a human hair", "eye glasses", "a safety jacket", "a mobile phone", "a safety helmet"]]

for image_name in image_files:
    image_path = os.path.join(dataset_folder, image_name)
    image = Image.open(image_path).convert("RGB")

    # Preprocess input
    inputs = processor(images=[image], text=text_labels, return_tensors="pt").to(device)

    # Run inference without gradient calculations
    with torch.no_grad():
        outputs = model(**inputs)

    print(f"Processed: {image_name}")

for image_name in image_files:
    image_path = os.path.join(dataset_folder, image_name)
    image = Image.open(image_path).convert("RGB")

    # Preprocess input
    inputs = processor(images=[image], text=text_labels, return_tensors="pt").to(device)

    # Run inference without gradient calculations
    with torch.no_grad():
        outputs = model(**inputs)

    # Convert outputs into human-readable results
    results = processor.post_process_grounded_object_detection(
        outputs,
        inputs.input_ids,
        box_threshold=0.5,
        text_threshold=0.3,
        target_sizes=[image.size[::-1]]
    )

    # Display detected objects
    result = results[0]
    print(f"Results for {image_name}:")
    for box, score, label in zip(result["boxes"], result["scores"], result["labels"]):
        box = [round(x, 2) for x in box.tolist()]
        print(f"Detected {label} with confidence {round(score.item(), 3)} at location {box}")

    print("-" * 50)  # Separator for better readability

import matplotlib.pyplot as plt
import matplotlib.patches as patches

for image_name in image_files:
    image_path = os.path.join(dataset_folder, image_name)
    image = Image.open(image_path).convert("RGB")

    # Preprocess input
    inputs = processor(images=[image], text=text_labels, return_tensors="pt").to(device)

    # Run inference without gradient calculations
    with torch.no_grad():
        outputs = model(**inputs)

    # Convert outputs into human-readable results
    results = processor.post_process_grounded_object_detection(
        outputs,
        inputs.input_ids,
        box_threshold=0.5,
        text_threshold=0.3,
        target_sizes=[image.size[::-1]]
    )

    # Display detected objects
    result = results[0]

    # Plot image
    fig, ax = plt.subplots(1, figsize=(8, 6))
    ax.imshow(image)

    # Draw bounding boxes
    for box, score, label in zip(result["boxes"], result["scores"], result["labels"]):
        x_min, y_min, x_max, y_max = box.tolist()
        width, height = x_max - x_min, y_max - y_min

        # Create a rectangle
        rect = patches.Rectangle((x_min, y_min), width, height, linewidth=2, edgecolor='red', facecolor='none')
        ax.add_patch(rect)
        ax.text(x_min, y_min - 5, f"{label}: {round(score.item(), 2)}", color='red', fontsize=12, fontweight='bold')

    plt.show()

import matplotlib.pyplot as plt
import matplotlib.patches as patches

# Convert image to RGB (if needed)
image = image.convert("RGB")

# Define output text file
output_file = "bounding_boxes.txt"

# Open the file to write bounding box details
with open(output_file, "w") as f:
    for box, score, label in zip(result["boxes"], result["scores"], result["labels"]):
        x_min, y_min, x_max, y_max = box.tolist()
        width, height = x_max - x_min, y_max - y_min

        # Write to file
        f.write(f"{label}, {score.item()}, {x_min}, {y_min}, {x_max}, {y_max}\n")

        # Draw bounding box on the image
        fig, ax = plt.subplots(1, figsize=(8, 6))
        ax.imshow(image)
        rect = patches.Rectangle((x_min, y_min), width, height, linewidth=2, edgecolor='red', facecolor='none')
        ax.add_patch(rect)
        ax.text(x_min, y_min - 5, f"{label}: {round(score.item(), 2)}", color='red', fontsize=12, fontweight='bold')

plt.show()

print(f"Bounding box coordinates saved to {output_file}")

import os
import matplotlib.pyplot as plt
import matplotlib.patches as patches
from PIL import Image

# Define class mapping
class_mapping = {
    "a remote control": 1,
    "a human head": 2,
    "a human hair": 3,
    "eye glasses": 4,
    "a safety jacket": 5,
    "a mobile phone": 6,
    "a safety helmet": 7
}

# Create a directory for bounding box text files if it doesn't exist
output_folder = "bounding_boxes"
os.makedirs(output_folder, exist_ok=True)

# Process each image in the dataset
for image_name in image_files:
    image_path = os.path.join(dataset_folder, image_name)
    image = Image.open(image_path).convert("RGB")
    W, H = image.size  # Get image width and height

    # Preprocess input
    inputs = processor(images=[image], text=list(class_mapping.keys()), return_tensors="pt").to(device)

    # Run inference without gradient calculations
    with torch.no_grad():
        outputs = model(**inputs)

    # Convert outputs into human-readable results
    results = processor.post_process_grounded_object_detection(
        outputs,
        inputs.input_ids,
        threshold=0.5,  # Use 'threshold' instead of 'box_threshold'
        text_threshold=0.3,
        target_sizes=[image.size[::-1]]
    )

    # Create a separate text file for each image
    output_file = os.path.join(output_folder, f"{os.path.splitext(image_name)[0]}.txt")

    with open(output_file, "w") as f:
        result = results[0]

        for box, label in zip(result["boxes"], result["labels"]):
            x_min, y_min, x_max, y_max = box.tolist()

            # Convert label text to class ID
            class_id = class_mapping.get(label, 0)  # Default to 0 if label not found

            # Convert to YOLO format (normalized)
            x_center = ((x_min + x_max) / 2) / W
            y_center = ((y_min + y_max) / 2) / H
            width = (x_max - x_min) / W
            height = (y_max - y_min) / H

            # Write YOLO format bounding box to file
            f.write(f"{class_id} {x_center:.6f} {y_center:.6f} {width:.6f} {height:.6f}\n")

            # Draw bounding box on the image
            fig, ax = plt.subplots(1, figsize=(8, 6))
            ax.imshow(image)
            rect = patches.Rectangle((x_min, y_min), (x_max - x_min), (y_max - y_min), linewidth=2, edgecolor='red', facecolor='none')
            ax.add_patch(rect)
            ax.text(x_min, y_min - 5, f"{class_id}", color='red', fontsize=12, fontweight='bold')

            plt.show()

print(f"Bounding box coordinates saved in the '{output_folder}' folder.")

